version: '3.8'

services:
  agent-factory:
    build: .
    ports:
      - "8004:8000"
    environment:
      - STORAGE_BACKEND=minio
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-yourusername}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-yourpassword}
      - AWS_ENDPOINT_URL=http://minio:9000
      - S3_BUCKET_NAME=agents
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - minio
    networks:
      - agent-network

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9091:9091"
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID:-yourusername}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY:-yourpassword}
    command: server /data --console-address ":9091"
    volumes:
      - minio-data:/data
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge

volumes:
  minio-data: